window.COURSE = {
  title: "Professional Java Programming Training Course",
  subtitle: "Java Package · Broadway Infosys",
  modules: [
    {
      id: "0",
      title: "Meet your trainer",
      lessons: [
        {
          id: "Intro",
          title: "Dharma Raj Thanait",
          href: "intro/my-introduction.html",
          ready: true,
          topics: ["Who I am", "Industry experience"],
        },
      ],
    },
    {
      id: "1",
      title: "Lesson 1: Desktop Based Applications Using Core Java",
      lessons: [
        {
          id: "1.1",
          title: "Introduction",
          href: "lessons/1.1-introduction.html",
          ready: true,
          topics: [
            "Language and platform",
            "Class and object",
            "Write once, run everywhere",
            "Download and setup",
            "Hello World",
          ],
        },
        {
          id: "1.2",
          title: "Data Type and Control Flow",
          href: "lessons/1.2-data-types-control-flow.html",
          ready: true,
          topics: [
            "Data types",
            "Wrappers",
            "Conditions",
            "Loops",
            "switch",
            "enum",
            "Conversion",
          ],
        },
        {
          id: "1.3",
          title: "String",
          href: "lessons/1.3-string.html",
          ready: true,
          topics: [
            "String class",
            "Methods",
            "Immutable",
            "String pool",
            "StringBuilder",
            "StringBuffer",
          ],
        },
        {
          id: "1.3b",
          title: "Array and Methods",
          href: "lessons/1.3b-array-methods.html",
          ready: true,
          topics: [
            "Methods and types",
            "Array",
            "Arrays class",
            "Array with methods",
            "Naming conventions",
          ],
        },
        {
          id: "1.4",
          title: "Object Oriented Programming",
          href: "lessons/1.4-oop.html",
          ready: true,
          topics: [
            "Class and objects",
            "Constructor",
            "Encapsulation",
            "this",
            "Has-a",
            "Static",
          ],
        },
        {
          id: "1.5",
          title: "Inheritance & Polymorphism",
          href: "lessons/1.5-inheritance.html",
          ready: true,
          topics: [
            "Inheritance",
            "Overload / override",
            "super and final",
            "Polymorphism",
            "Abstract",
            "Interfaces",
          ],
        },
        {
          id: "1.6",
          title: "Exception Handling",
          href: "lessons/1.6-exception.html",
          ready: true,
          topics: [
            "try / catch",
            "throw / throws",
            "Custom exception",
            "finally",
          ],
        },
        {
          id: "1.7",
          title: "File IO",
          href: "lessons/1.7-file-io.html",
          ready: true,
          topics: [
            "File",
            "FileWriter / FileReader",
            "Data streams",
            "Scanner tokens",
            "RandomAccessFile",
            "Student project",
          ],
        },
        {
          id: "1.8",
          title: "Multithreading",
          href: "lessons/1.8-multithreading.html",
          ready: true,
          topics: [
            "Process vs Thread",
            "start vs run",
            "sleep / join",
            "Sync",
            "Pools",
          ],
        },
        {
          id: "1.9",
          title: "Collection Classes",
          href: "lessons/1.9-collections.html",
          ready: true,
          topics: [
            "Why collections",
            "List / ArrayList",
            "LinkedList",
            "Set / HashSet",
            "Map / HashMap",
            "Collections vs Arrays",
            "instanceof",
          ],
        },
        {
          id: "1.10",
          title: "Java 8",
          href: "lessons/1.10-java8.html",
          ready: true,
          topics: [
            "What Java 8 is",
            "stream()",
            "filter / map",
            "forEach / collect",
            "LocalDate / LocalTime",
            "Format and plus/minus",
          ],
        },
        { id: "1.11", title: "Swing GUI Widgets", topics: ["JFrame", "Buttons", "Listeners"] },
        { id: "1.12", title: "Intermediate Swing", topics: ["Lists", "Tables", "Text fields"] },
        { id: "1.13", title: "Designing GUIs", topics: ["Fonts", "Look and Feel", "Layouts"] },
        {
          id: "1.14",
          title: "JDBC",
          href: "lessons/1.14-jdbc.html",
          ready: true,
          topics: [
            "Why store data",
            "Files vs database",
            "Tables and keys",
            "JDBC",
            "Driver",
            "Connection",
            "Student CRUD",
          ],
        },
        { id: "1.15", title: "Final Project: Core Java", topics: ["Assignments", "Swing calculator", "CRUD desktop app", "Inventory"] },
      ],
    },
    {
      id: "2",
      title: "Lesson 2: Advanced Java Training (Web Applications)",
      lessons: [
        { id: "2.1", title: "Introduction", topics: ["J2EE/JEE", "HTTP", "Tomcat"] },
        { id: "2.2", title: "JSP Servlets", topics: ["Servlet lifecycle", "JSP", "JSTL", "Bootstrap project"] },
        { id: "2.3", title: "Maven", topics: ["POM", "Lifecycle", "Repositories"] },
        { id: "2.4", title: "Hibernate Framework", topics: ["ORM", "Session", "Criteria", "hbm2ddl"] },
        { id: "2.5", title: "Spring Framework", topics: ["Spring vs Java EE", "AOP", "Modules"] },
        { id: "2.6", title: "Spring Dependency Injection", topics: ["IoC", "Constructor/Setter", "ApplicationContext"] },
        { id: "2.7", title: "Design Pattern", topics: ["Factory", "Singleton", "MVC", "Builder", "Decorator"] },
        { id: "2.8", title: "Spring Boot Basic", topics: ["Annotations", "Starters", "Properties"] },
        { id: "2.9", title: "Spring Boot DevTools", topics: ["Hot reload"] },
        { id: "2.10", title: "Spring Boot Data JPA", topics: ["Repositories", "findBy", "@Query"] },
        { id: "2.11", title: "Spring Boot MVC", topics: ["Controllers", "Views", "Upload", "JDBCTemplate"] },
        { id: "2.12", title: "LOG4J Framework", topics: ["Levels", "Config", "Formatting"] },
        { id: "2.13", title: "Lombok API", topics: ["@Data", "@Slf4j", "Constructors"] },
        { id: "2.14", title: "Spring REST Services", topics: ["REST", "JSON", "POSTMAN", "RestTemplate"] },
        { id: "2.15", title: "Spring Boot Security", topics: ["AuthN/AuthZ", "Roles", "JPA auth"] },
        { id: "2.16", title: "Spring Boot Email", topics: ["JavaMail", "Mime attachments"] },
        { id: "2.17", title: "Spring Boot with Swagger", topics: ["Swagger UI", "REST docs"] },
        { id: "2.18", title: "Spring Cloud", topics: ["AWS deploy", "Recaptcha", "Facebook login"] },
        { id: "2.19", title: "JUnit", topics: ["Assertions", "@Before", "@Test"] },
        { id: "2.20", title: "Spring Boot With AI", topics: ["OpenAI", "Ollama"] },
        { id: "2.21", title: "Micro Services", topics: ["Sync/Async", "Design", "Pitfalls"] },
        { id: "2.22", title: "Demo: Advance Java & Framework", topics: ["Servlet", "JSP", "MVC", "REST", "Hibernate"] },
        { id: "2.23", title: "Final Project: Advance Java", topics: ["Spring MVC + Hibernate + Maven"] },
        { id: "2.24", title: "Example Projects", topics: ["SIMS", "Shopping Cart", "Share Trading", "Online Banking"] },
      ],
    },
  ],
};
