window.LABS = [
  {
    id: "1.1",
    title: "Introduction",
    folder: "1.1",
    slides: "lessons/1.1-introduction.html",
    files: ["HelloWorld.java", "PrintArgs.java"],
  },
  {
    id: "1.2",
    title: "Data Type and Control Flow",
    folder: "1.2",
    slides: "lessons/1.2-data-types-control-flow.html",
    files: [
      "TypesDemo.java",
      "IfLogic.java",
      "LoopsDemo.java",
      "SwitchDemo.java",
      "BreakContinueReturn.java",
    ],
  },
  {
    id: "1.3",
    title: "String",
    folder: "1.3-string",
    slides: "lessons/1.3-string.html",
    files: [
      "StringBasics.java",
      "StringMethods.java",
      "ImmutabilityDemo.java",
      "StringPoolDemo.java",
      "BuilderBufferDemo.java",
      "StudentEntry.java",
    ],
  },
  {
    id: "1.3b",
    title: "Array and Methods",
    folder: "1.3-array",
    slides: "lessons/1.3b-array-methods.html",
    files: [
      "WhyMethods.java",
      "SquareReuse.java",
      "MethodsDemo.java",
      "ArrayDemo.java",
      "ArraysFillSearch.java",
      "StudentMarks.java",
    ],
  },
  {
    id: "1.4",
    title: "Object Oriented Programming",
    folder: "1.4",
    slides: "lessons/1.4-oop.html",
    files: [
      "AccountObjects.java",
      "AccountMethods.java",
      "ConstructorEncaps.java",
      "StudentAddress.java",
      "StaticUses.java",
      "StaticBlockDemo.java",
    ],
  },
  {
    id: "1.5",
    title: "Inheritance and Polymorphism",
    folder: "1.5",
    slides: "lessons/1.5-inheritance.html",
    files: [
      "EncapsulateAnimal.java",
      "InheritDog.java",
      "InheritTypes.java",
      "OverrideSound.java",
      "SuperDemo.java",
      "FinalDemo.java",
      "PolyAnimal.java",
      "PolyLoop.java",
      "PolyNewType.java",
      "AbstractAnimal.java",
      "CanSwim.java",
      "ObjectToString.java",
    ],
  },
  {
    id: "1.6",
    title: "Exception Handling",
    folder: "1.6",
    slides: "lessons/1.6-exception.html",
    files: [
      "DivideByZero.java",
      "DivideCalculator.java",
      "NullPointerCatch.java",
      "CommonExceptions.java",
      "MultiCatch.java",
      "FinallyDemo.java",
      "ThrowVsThrows.java",
      "Propagation.java",
      "InsufficientBalance.java",
    ],
  },
  {
    id: "1.7",
    title: "File IO",
    folder: "1.7",
    slides: "lessons/1.7-file-io.html",
    files: [
      "FileManage.java",
      "WriteNames.java",
      "ReadNames.java",
      "DataWrite.java",
      "DataRead.java",
      "TokenRead.java",
      "JumpRead.java",
      "StudentFileManager.java",
    ],
  },
  {
    id: "1.8",
    title: "Multithreading",
    folder: "1.8",
    slides: "lessons/1.8-multithreading.html",
    files: [
      "ExtendThread.java",
      "ImplementRunnable.java",
      "StartVsRun.java",
      "SleepDemo.java",
      "JoinDemo.java",
      "RaceCounter.java",
      "SyncCounter.java",
      "PoolDemo.java",
      "PaymentWorkers.java",
    ],
  },
  {
    id: "1.9",
    title: "Collection Classes",
    folder: "1.9",
    slides: "lessons/1.9-collections.html",
    files: [
      "ArrayVsList.java",
      "ListDemo.java",
      "LinkedListEnds.java",
      "SetDemo.java",
      "MapDemo.java",
      "CollectionsUtil.java",
      "ArraysUtil.java",
      "InstanceOfDemo.java",
      "ChooseCollection.java",
    ],
  },
  {
    id: "1.10",
    title: "Java 8",
    folder: "1.10",
    slides: "lessons/1.10-java8.html",
    files: [
      "StreamForEach.java",
      "StreamFilter.java",
      "StreamMap.java",
      "StreamPipeline.java",
      "TodayDate.java",
      "FormatDate.java",
      "DateMath.java",
      "CompareDates.java",
    ],
  },
  {
    id: "1.14",
    title: "JDBC",
    folder: "1.14",
    slides: "lessons/1.14-jdbc.html",
    files: [
      "ConnectDemo.java",
      "CreateDatabase.java",
      "CreateStudentTable.java",
      "InsertStudent.java",
      "ViewStudents.java",
      "UpdateStudent.java",
      "DeleteStudent.java",
    ],
  },
  {
    id: "2.2",
    title: "Introduction to JEE, Servlets and JSP",
    folder: "2.2",
    slides: "lessons/2.2-servlets-jsp.html",
    files: [
      "HelloServlet.java",
      "register.html",
      "StudentServlet.java",
      "welcome.jsp",
    ],
    urls: {
      "HelloServlet.java": "http://localhost:8080/StudentApp/hello",
      "register.html": "http://localhost:8080/StudentApp/register.html",
      "StudentServlet.java": "http://localhost:8080/StudentApp/register",
      "welcome.jsp": "http://localhost:8080/StudentApp/welcome.jsp",
    },
  },
  {
    id: "2.3",
    title: "Maven",
    folder: "2.3",
    slides: "lessons/2.3-maven.html",
    files: [
      "mysql-maven-demo/pom.xml",
      "mysql-maven-demo/src/main/java/com/example/Main.java",
    ],
    commands: {
      "mysql-maven-demo/pom.xml": "cd coding/2.3/mysql-maven-demo && mvn compile",
      "mysql-maven-demo/src/main/java/com/example/Main.java": "cd coding/2.3/mysql-maven-demo && mvn package",
    },
  },
  {
    id: "2.4",
    title: "Hibernate",
    folder: "2.4/student-app",
    slides: "lessons/2.4-hibernate.html",
    files: [
      "pom.xml",
      "src/main/resources/hibernate.cfg.xml",
      "src/main/java/com/example/Student.java",
      "src/main/java/com/example/HibernateUtil.java",
      "src/main/java/com/example/ConnectDemo.java",
    ],
    commands: {
      "pom.xml": "cd coding/2.4/student-app && mvn -q compile",
      "src/main/resources/hibernate.cfg.xml": "cd coding/2.4/student-app && mvn -q compile",
      "src/main/java/com/example/Student.java": "cd coding/2.4/student-app && mvn -q compile",
      "src/main/java/com/example/HibernateUtil.java": "cd coding/2.4/student-app && mvn -q compile",
      "src/main/java/com/example/ConnectDemo.java": "cd coding/2.4/student-app && mvn -q compile exec:java -Dexec.mainClass=com.example.ConnectDemo",
    },
  },
  {
    id: "2.4b",
    title: "Hibernate CRUD",
    folder: "2.4/student-app",
    slides: "lessons/2.4b-hibernate-crud.html",
    files: [
      "src/main/java/com/example/InsertStudent.java",
      "src/main/java/com/example/FindStudent.java",
      "src/main/java/com/example/UpdateStudent.java",
      "src/main/java/com/example/DeleteStudent.java",
      "src/main/java/com/example/ListStudents.java",
      "src/main/java/com/example/SearchStudent.java",
    ],
    commands: {
      "src/main/java/com/example/InsertStudent.java": "cd coding/2.4/student-app && mvn -q compile exec:java -Dexec.mainClass=com.example.InsertStudent",
      "src/main/java/com/example/FindStudent.java": "cd coding/2.4/student-app && mvn -q compile exec:java -Dexec.mainClass=com.example.FindStudent",
      "src/main/java/com/example/UpdateStudent.java": "cd coding/2.4/student-app && mvn -q compile exec:java -Dexec.mainClass=com.example.UpdateStudent",
      "src/main/java/com/example/DeleteStudent.java": "cd coding/2.4/student-app && mvn -q compile exec:java -Dexec.mainClass=com.example.DeleteStudent",
      "src/main/java/com/example/ListStudents.java": "cd coding/2.4/student-app && mvn -q compile exec:java -Dexec.mainClass=com.example.ListStudents",
      "src/main/java/com/example/SearchStudent.java": "cd coding/2.4/student-app && mvn -q compile exec:java -Dexec.mainClass=com.example.SearchStudent",
    },
  },
];
